-- =====================================================
-- BASE TABLE: USERS (Base entity for admin, doctor, patient)
-- =====================================================
CREATE TABLE USERS (
    USER_ID        NUMBER GENERATED ALWAYS AS IDENTITY,
    NAME           VARCHAR2(100)        NOT NULL,
    EMAIL          VARCHAR2(150)        UNIQUE NOT NULL,
    PASSWORD       VARCHAR2(200)        NOT NULL,
    ROLE           VARCHAR2(50)
                    CHECK (ROLE IN ('ADMIN', 'DOCTOR', 'PATIENT')),
    CONTACT_NO     VARCHAR2(15),
    CREATED_ON     DATE DEFAULT SYSDATE,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);

-- =====================================================
-- TABLE: DOCTORS (specialization of USERS)
-- =====================================================
CREATE TABLE DOCTORS (
    DOCTOR_ID      NUMBER GENERATED ALWAYS AS IDENTITY,
    USER_ID        NUMBER NOT NULL,
    SPECIALIZATION VARCHAR2(100),
    AVAILABLE_FROM TIMESTAMP,
    AVAILABLE_TO   TIMESTAMP,
    EXPERIENCE_YRS NUMBER(3),
    QUALIFICATION  VARCHAR2(100),
    CONSTRAINT PK_DOCTORS PRIMARY KEY (DOCTOR_ID),
    CONSTRAINT FK_DOCTORS_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);

-- =====================================================
-- TABLE: PATIENTS (specialization of USERS)
-- =====================================================
CREATE TABLE PATIENTS (
    PATIENT_ID        NUMBER GENERATED ALWAYS AS IDENTITY,
    USER_ID           NUMBER NOT NULL,
    GENDER            VARCHAR2(10)
                       CHECK (GENDER IN ('Male', 'Female', 'Other')),
    DATE_OF_BIRTH     DATE,
    BLOOD_GROUP       VARCHAR2(5),
    ADDRESS           VARCHAR2(255),
    CITY              VARCHAR2(100),
    STATE             VARCHAR2(100),
    ZIP_CODE          VARCHAR2(12),
    EMERGENCY_CONTACT VARCHAR2(15),
    ALLERGIES         VARCHAR2(255),
    MEDICAL_HISTORY   CLOB,
    INSURANCE_ID      VARCHAR2(50),
    INSURANCE_PROVIDER VARCHAR2(100),
    CONSTRAINT PK_PATIENTS PRIMARY KEY (PATIENT_ID),
    CONSTRAINT FK_PATIENTS_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);

-- =====================================================
-- TABLE: APPOINTMENTS
-- =====================================================
CREATE TABLE APPOINTMENTS (
    APPOINTMENT_ID   NUMBER GENERATED ALWAYS AS IDENTITY,
    PATIENT_ID       NUMBER NOT NULL,
    DOCTOR_ID        NUMBER NOT NULL,
    APPT_DATE        TIMESTAMP NOT NULL,
    DURATION_MIN     NUMBER(4),
    STATUS           VARCHAR2(50) DEFAULT 'SCHEDULED'
                      CHECK (STATUS IN ('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    REASON           VARCHAR2(255),
    CREATED_ON       DATE DEFAULT SYSDATE,
    CONSTRAINT PK_APPOINTMENTS PRIMARY KEY (APPOINTMENT_ID),
    CONSTRAINT FK_APPT_PATIENT FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENTS (PATIENT_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_APPT_DOCTOR FOREIGN KEY (DOCTOR_ID)
        REFERENCES DOCTORS (DOCTOR_ID)
        ON DELETE CASCADE,
    CONSTRAINT UQ_APPT_UNIQUE UNIQUE (PATIENT_ID, DOCTOR_ID, APPT_DATE)
);

-- =====================================================
-- TABLE: PRESCRIPTIONS
-- =====================================================
CREATE TABLE PRESCRIPTIONS (
    PRESCRIPTION_ID  NUMBER GENERATED ALWAYS AS IDENTITY,
    APPOINTMENT_ID   NUMBER UNIQUE NOT NULL,
    PRESCRIBED_BY    NUMBER NULL,
    NOTES            CLOB,
    CREATED_ON       DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PRESCRIPTIONS PRIMARY KEY (PRESCRIPTION_ID),
    CONSTRAINT FK_PRESC_APPT FOREIGN KEY (APPOINTMENT_ID)
        REFERENCES APPOINTMENTS (APPOINTMENT_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_PRESC_DOCTOR FOREIGN KEY (PRESCRIBED_BY)
        REFERENCES DOCTORS (DOCTOR_ID)
        ON DELETE SET NULL
);

-- =====================================================
-- TABLE: MEDICINE
-- =====================================================
CREATE TABLE MEDICINE (
    MEDICINE_ID   NUMBER GENERATED ALWAYS AS IDENTITY,
    NAME          VARCHAR2(100) NOT NULL,
    FORM          VARCHAR2(50)
                   CHECK (FORM IN ('Tablet', 'Capsule', 'Syrup', 'Injection', 'Ointment')),
    DETAILS       VARCHAR2(255),
    CONSTRAINT PK_MEDICINE PRIMARY KEY (MEDICINE_ID),
    CONSTRAINT UQ_MEDICINE_NAME UNIQUE (NAME)
);

-- =====================================================
-- TABLE: PRESCRIPTION_MED (Many-to-Many link)
-- =====================================================
CREATE TABLE PRESCRIPTION_MED (
    PRESCRIPTION_ID  NUMBER NOT NULL,
    MEDICINE_ID      NUMBER NOT NULL,
    DOSE             VARCHAR2(50),
    DURATION         VARCHAR2(50),
    INSTRUCTIONS     VARCHAR2(255),
    CONSTRAINT PK_PRESCRIPTION_MED PRIMARY KEY (PRESCRIPTION_ID, MEDICINE_ID),
    CONSTRAINT FK_PM_PRESCRIPTION FOREIGN KEY (PRESCRIPTION_ID)
        REFERENCES PRESCRIPTIONS (PRESCRIPTION_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_PM_MEDICINE FOREIGN KEY (MEDICINE_ID)
        REFERENCES MEDICINE (MEDICINE_ID)
        ON DELETE CASCADE
);

-- =====================================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- (Removed indexes that support features not used by the app: role-based search, specialization search,
--  availability-range searches and patient city/state/insurance search)
-- =====================================================

-- Keep email index for login lookups
CREATE INDEX IDX_USERS_EMAIL ON USERS (EMAIL);

-- Keep indexes that support common foreign-key lookups used by the app
CREATE INDEX IDX_DOCTORS_USERID ON DOCTORS (USER_ID);
CREATE INDEX IDX_PATIENTS_USERID ON PATIENTS (USER_ID);

-- Appointment lookups by patient/doctor and status/date for typical queries
CREATE INDEX IDX_APPT_PATIENT ON APPOINTMENTS (PATIENT_ID);
CREATE INDEX IDX_APPT_DOCTOR ON APPOINTMENTS (DOCTOR_ID);
CREATE INDEX IDX_APPT_STATUS_DATE ON APPOINTMENTS (STATUS, APPT_DATE);

-- Prescription and medicine lookup indexes
CREATE INDEX IDX_PRESC_APPT ON PRESCRIPTIONS (APPOINTMENT_ID);
CREATE INDEX IDX_PRESC_DOCTOR ON PRESCRIPTIONS (PRESCRIBED_BY);
CREATE INDEX IDX_MEDICINE_NAME ON MEDICINE (NAME);

-- Prescription-Med join indexes
CREATE INDEX IDX_PM_PRESCRIPTION ON PRESCRIPTION_MED (PRESCRIPTION_ID);
CREATE INDEX IDX_PM_MEDICINE ON PRESCRIPTION_MED (MEDICINE_ID);
